-- ================================================================================
-- 04_business_queries.sql
-- --------------------------------------------------------------------------------
-- AI-Powered E-commerce Customer & Sales Analytics Platform
-- 42 business questions answered in SQL (MySQL 8.0+ syntax).
-- Every query is preceded by a comment explaining the business question it
-- answers and the SQL technique it demonstrates.
-- Run after 01_create_schema.sql, 02_load_data.sql, 03_indexes_and_views.sql.
-- ================================================================================

USE ecommerce_analytics;


-- ================================================================================
-- SECTION A: BASIC SELECT / FILTER / SORT
-- ================================================================================

-- Q1. [BASIC] Which products belong to the Electronics category?
SELECT Product_ID, Product_Name, Brand, Unit_Price
FROM products
WHERE Category = 'Electronics'
ORDER BY Unit_Price DESC;

-- Q2. [BASIC] Which orders were placed in July 2026?
SELECT Order_ID, Customer_ID, Order_Date, Total_Sales
FROM orders
WHERE Order_Date BETWEEN '2026-07-01' AND '2026-07-31'
ORDER BY Order_Date;

-- Q3. [BASIC] Who are the customers located in Texas?
SELECT Customer_ID, First_Name, Last_Name, City, Customer_Segment
FROM customers
WHERE State = 'Texas';

-- Q4. [BASIC] What are the 10 highest-priced products in the catalog?
SELECT Product_ID, Product_Name, Category, Unit_Price
FROM products
ORDER BY Unit_Price DESC
LIMIT 10;

-- Q5. [BASIC] Which orders were cancelled?
SELECT Order_ID, Customer_ID, Order_Date, Total_Sales
FROM orders
WHERE Order_Status = 'Cancelled';


-- ================================================================================
-- SECTION B: GROUP BY / AGGREGATION
-- ================================================================================

-- Q6. [GROUP BY] What is total revenue generated by each category?
SELECT Category, ROUND(SUM(Sales), 2) AS Total_Sales
FROM order_items
GROUP BY Category
ORDER BY Total_Sales DESC;

-- Q7. [GROUP BY] How many orders does each customer segment place?
SELECT c.Customer_Segment, COUNT(o.Order_ID) AS Order_Count
FROM customers c
JOIN orders o ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_Segment
ORDER BY Order_Count DESC;

-- Q8. [GROUP BY] What is the average review score per product?
SELECT Product_ID, ROUND(AVG(Review_Score), 2) AS Avg_Score, COUNT(*) AS Review_Count
FROM reviews
GROUP BY Product_ID
ORDER BY Avg_Score DESC;

-- Q9. [GROUP BY] What is total revenue by state?
SELECT c.State, ROUND(SUM(oi.Sales), 2) AS Total_Sales
FROM customers c
JOIN orders o       ON c.Customer_ID = o.Customer_ID
JOIN order_items oi ON o.Order_ID = oi.Order_ID
GROUP BY c.State
ORDER BY Total_Sales DESC;

-- Q10. [GROUP BY] How many orders were paid through each payment method?
SELECT Payment_Method, COUNT(*) AS Order_Count
FROM orders
GROUP BY Payment_Method
ORDER BY Order_Count DESC;


-- ================================================================================
-- SECTION C: HAVING (post-aggregation filters)
-- ================================================================================

-- Q11. [HAVING] Which categories generate more than $1,000,000 in total sales?
SELECT Category, ROUND(SUM(Sales), 2) AS Total_Sales
FROM order_items
GROUP BY Category
HAVING SUM(Sales) > 1000000
ORDER BY Total_Sales DESC;

-- Q12. [HAVING] Which customers have placed more than 5 orders (high engagement)?
SELECT Customer_ID, COUNT(Order_ID) AS Order_Count
FROM orders
GROUP BY Customer_ID
HAVING COUNT(Order_ID) > 5
ORDER BY Order_Count DESC;

-- Q13. [HAVING] Which states have an average order value above $1,200?
SELECT c.State, ROUND(AVG(o.Total_Sales), 2) AS Avg_Order_Value
FROM customers c
JOIN orders o ON c.Customer_ID = o.Customer_ID
GROUP BY c.State
HAVING AVG(o.Total_Sales) > 1200
ORDER BY Avg_Order_Value DESC;


-- ================================================================================
-- SECTION D: CASE WHEN (business rules / bucketing)
-- ================================================================================

-- Q14. [CASE WHEN] Classify each order line into a discount tier.
SELECT
    Order_Item_ID, Discount,
    CASE
        WHEN Discount = 0 THEN 'No Discount'
        WHEN Discount <= 0.10 THEN 'Low (0-10%)'
        WHEN Discount <= 0.20 THEN 'Medium (10-20%)'
        ELSE 'High (20%+)'
    END AS Discount_Tier
FROM order_items;

-- Q15. [CASE WHEN] Label each customer's value tier based on lifetime value.
SELECT
    Customer_ID, Customer_Lifetime_Value,
    CASE
        WHEN Customer_Lifetime_Value >= 5000 THEN 'High Value'
        WHEN Customer_Lifetime_Value >= 1500 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS Value_Tier
FROM customers;

-- Q16. [CASE WHEN] Flag each shipped order's delivery speed.
SELECT
    Order_ID, Delivery_Days,
    CASE
        WHEN Delivery_Days <= 3 THEN 'Fast'
        WHEN Delivery_Days <= 6 THEN 'Normal'
        ELSE 'Slow'
    END AS Delivery_Speed
FROM orders
WHERE Delivery_Days IS NOT NULL;


-- ================================================================================
-- SECTION E: JOINS
-- ================================================================================

-- Q17. [JOIN - INNER] Full order line detail with customer name and location.
SELECT oi.Order_Item_ID, o.Order_Date, c.First_Name, c.Last_Name, c.State,
       oi.Category, oi.Sales
FROM order_items oi
INNER JOIN orders o    ON oi.Order_ID = o.Order_ID
INNER JOIN customers c ON o.Customer_ID = c.Customer_ID;

-- Q18. [JOIN - LEFT / anti-join] Which products have NEVER been ordered?
SELECT p.Product_ID, p.Product_Name, p.Category
FROM products p
LEFT JOIN order_items oi ON p.Product_ID = oi.Product_ID
WHERE oi.Order_Item_ID IS NULL;

-- Q19. [JOIN] What is each customer's most recent order date?
SELECT c.Customer_ID, c.First_Name, c.Last_Name, MAX(o.Order_Date) AS Last_Order_Date
FROM customers c
JOIN orders o ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID, c.First_Name, c.Last_Name;

-- Q20. [JOIN] Which carrier shipped each order, and how many days did it take?
SELECT o.Order_ID, s.Carrier, s.Shipping_Mode, s.Delivery_Days
FROM orders o
JOIN shipping s ON o.Order_ID = s.Order_ID;

-- Q21. [JOIN - multi-table] Full 360-degree view: order + product + customer.
SELECT o.Order_ID, o.Order_Date, c.First_Name, c.Last_Name, c.State,
       p.Product_Name, oi.Quantity, oi.Sales, oi.Profit
FROM orders o
JOIN customers c    ON o.Customer_ID = c.Customer_ID
JOIN order_items oi ON o.Order_ID = oi.Order_ID
JOIN products p     ON oi.Product_ID = p.Product_ID;


-- ================================================================================
-- SECTION F: SUBQUERIES
-- ================================================================================

-- Q22. [SUBQUERY] Which customers spent more than the average customer?
SELECT Customer_ID, Total_Spend
FROM customers
WHERE Total_Spend > (SELECT AVG(Total_Spend) FROM customers);

-- Q23. [SUBQUERY - correlated] Which products are priced above their own
--      category's average price?
SELECT p.Product_ID, p.Product_Name, p.Category, p.Unit_Price
FROM products p
WHERE p.Unit_Price > (
    SELECT AVG(p2.Unit_Price)
    FROM products p2
    WHERE p2.Category = p.Category
);

-- Q24. [SUBQUERY] Which orders sold above the overall average order value?
SELECT Order_ID, Customer_ID, Total_Sales
FROM orders
WHERE Total_Sales > (SELECT AVG(Total_Sales) FROM orders);

-- Q25. [SUBQUERY - correlated] Who is the single top-spending customer in
--      each state?
SELECT c.State, c.Customer_ID, c.Total_Spend
FROM customers c
WHERE c.Total_Spend = (
    SELECT MAX(c2.Total_Spend)
    FROM customers c2
    WHERE c2.State = c.State
);


-- ================================================================================
-- SECTION G: CTEs (WITH clauses)
-- ================================================================================

-- Q26. [CTE] Month-over-month sales growth rate.
WITH monthly_sales AS (
    SELECT DATE_FORMAT(o.Order_Date, '%Y-%m') AS Year_Month,
           SUM(oi.Sales) AS Total_Sales
    FROM orders o
    JOIN order_items oi ON o.Order_ID = oi.Order_ID
    GROUP BY DATE_FORMAT(o.Order_Date, '%Y-%m')
)
SELECT
    Year_Month,
    Total_Sales,
    LAG(Total_Sales) OVER (ORDER BY Year_Month)                      AS Prev_Month_Sales,
    ROUND(
        (Total_Sales - LAG(Total_Sales) OVER (ORDER BY Year_Month))
        / LAG(Total_Sales) OVER (ORDER BY Year_Month) * 100, 1
    ) AS MoM_Growth_Pct
FROM monthly_sales
ORDER BY Year_Month;

-- Q27. [CTE] RFM base metrics per customer (Recency, Frequency, Monetary).
WITH rfm AS (
    SELECT
        o.Customer_ID,
        DATEDIFF((SELECT MAX(Order_Date) FROM orders), MAX(o.Order_Date)) AS Recency_Days,
        COUNT(DISTINCT o.Order_ID)  AS Frequency,
        SUM(oi.Sales)               AS Monetary
    FROM orders o
    JOIN order_items oi ON o.Order_ID = oi.Order_ID
    GROUP BY o.Customer_ID
)
SELECT * FROM rfm ORDER BY Monetary DESC;

-- Q28. [CTE] Rank categories by total profit.
WITH category_profit AS (
    SELECT Category, SUM(Profit) AS Total_Profit
    FROM order_items
    GROUP BY Category
)
SELECT Category, Total_Profit,
       RANK() OVER (ORDER BY Total_Profit DESC) AS Profit_Rank
FROM category_profit;

-- Q29. [CTE] Customers segmented by churn status with their total spend.
WITH customer_spend AS (
    SELECT c.Customer_ID, c.Churned, SUM(oi.Sales) AS Total_Spend
    FROM customers c
    JOIN orders o       ON c.Customer_ID = o.Customer_ID
    JOIN order_items oi ON o.Order_ID = oi.Order_ID
    GROUP BY c.Customer_ID, c.Churned
)
SELECT
    CASE WHEN Churned = 1 THEN 'Churned' ELSE 'Active' END AS Status,
    COUNT(*)                    AS Customer_Count,
    ROUND(AVG(Total_Spend), 2)  AS Avg_Spend
FROM customer_spend
GROUP BY Churned;


-- ================================================================================
-- SECTION H: WINDOW FUNCTIONS
-- ================================================================================

-- Q30. [WINDOW] Running (cumulative) total of monthly sales across the year.
SELECT
    DATE_FORMAT(o.Order_Date, '%Y-%m') AS Year_Month,
    SUM(oi.Sales) AS Monthly_Sales,
    SUM(SUM(oi.Sales)) OVER (ORDER BY DATE_FORMAT(o.Order_Date, '%Y-%m')) AS Running_Total
FROM orders o
JOIN order_items oi ON o.Order_ID = oi.Order_ID
GROUP BY DATE_FORMAT(o.Order_Date, '%Y-%m')
ORDER BY Year_Month;

-- Q31. [WINDOW] Rank products by sales WITHIN their own category.
SELECT
    Category, Product_ID,
    SUM(Sales) AS Product_Sales,
    RANK() OVER (PARTITION BY Category ORDER BY SUM(Sales) DESC) AS Rank_In_Category
FROM order_items
GROUP BY Category, Product_ID;

-- Q32. [WINDOW] Number each customer's orders in chronological sequence
--      (1st order, 2nd order, etc.) - useful for repeat-purchase analysis.
SELECT
    Customer_ID, Order_ID, Order_Date,
    ROW_NUMBER() OVER (PARTITION BY Customer_ID ORDER BY Order_Date) AS Order_Sequence
FROM orders;

-- Q33. [WINDOW] 3-month moving average of sales (smooths seasonality noise).
WITH monthly AS (
    SELECT DATE_FORMAT(o.Order_Date, '%Y-%m') AS Year_Month, SUM(oi.Sales) AS Total_Sales
    FROM orders o
    JOIN order_items oi ON o.Order_ID = oi.Order_ID
    GROUP BY DATE_FORMAT(o.Order_Date, '%Y-%m')
)
SELECT
    Year_Month, Total_Sales,
    ROUND(AVG(Total_Sales) OVER (
        ORDER BY Year_Month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ), 2) AS Moving_Avg_3M
FROM monthly
ORDER BY Year_Month;


-- ================================================================================
-- SECTION I: RANKING (Top-N per group)
-- ================================================================================

-- Q34. [RANKING] Top 5 products by revenue within EACH category.
WITH ranked AS (
    SELECT
        Category, Product_ID, SUM(Sales) AS Total_Sales,
        DENSE_RANK() OVER (PARTITION BY Category ORDER BY SUM(Sales) DESC) AS Rnk
    FROM order_items
    GROUP BY Category, Product_ID
)
SELECT Category, Product_ID, Total_Sales, Rnk
FROM ranked
WHERE Rnk <= 5
ORDER BY Category, Rnk;

-- Q35. [RANKING] Top 3 highest-spending customers within EACH state.
WITH ranked_customers AS (
    SELECT
        c.State, c.Customer_ID, SUM(oi.Sales) AS Total_Spend,
        RANK() OVER (PARTITION BY c.State ORDER BY SUM(oi.Sales) DESC) AS Rnk
    FROM customers c
    JOIN orders o       ON c.Customer_ID = o.Customer_ID
    JOIN order_items oi ON o.Order_ID = oi.Order_ID
    GROUP BY c.State, c.Customer_ID
)
SELECT State, Customer_ID, Total_Spend, Rnk
FROM ranked_customers
WHERE Rnk <= 3
ORDER BY State, Rnk;

-- Q36. [RANKING] Split customers into 4 equal-sized spend quartiles (NTILE).
SELECT
    Customer_ID, Total_Spend,
    NTILE(4) OVER (ORDER BY Total_Spend DESC) AS Spend_Quartile
FROM customers;


-- ================================================================================
-- SECTION J: STORED PROCEDURE
-- ================================================================================

-- Q37. [STORED PROCEDURE] Reusable lookup: full order history for one customer.
--      Usage:  CALL sp_customer_order_history('CUST00001');
DELIMITER $$

CREATE PROCEDURE sp_customer_order_history(IN p_customer_id VARCHAR(10))
BEGIN
    SELECT
        o.Order_ID,
        o.Order_Date,
        o.Order_Status,
        oi.Product_ID,
        oi.Category,
        oi.Quantity,
        oi.Sales,
        oi.Profit
    FROM orders o
    JOIN order_items oi ON o.Order_ID = oi.Order_ID
    WHERE o.Customer_ID = p_customer_id
    ORDER BY o.Order_Date DESC;
END$$

DELIMITER ;

-- Example call:
-- CALL sp_customer_order_history('CUST00001');


-- ================================================================================
-- SECTION K: USING THE VIEWS (from 03_indexes_and_views.sql)
-- ================================================================================

-- Q38. [VIEW] Top 20 customers by lifetime value, using vw_customer_ltv.
SELECT Customer_ID, First_Name, Last_Name, State, Total_Sales, Total_Orders
FROM vw_customer_ltv
ORDER BY Total_Sales DESC
LIMIT 20;

-- Q39. [VIEW] Year-over-year comparison using vw_monthly_sales.
SELECT
    Year_Month,
    Total_Sales,
    LEFT(Year_Month, 4) AS Yr
FROM vw_monthly_sales
ORDER BY Year_Month;


-- ================================================================================
-- SECTION L: BUSINESS KPI SUMMARIES
-- ================================================================================

-- Q40. [KPI] Company-wide headline metrics (for the Executive Dashboard).
SELECT
    ROUND(SUM(Sales), 2)                                    AS Total_Revenue,
    ROUND(SUM(Profit), 2)                                   AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 1)                AS Profit_Margin_Pct,
    (SELECT COUNT(DISTINCT Order_ID) FROM order_items)      AS Total_Orders,
    (SELECT COUNT(*) FROM customers)                        AS Total_Customers,
    ROUND(SUM(Sales) / (SELECT COUNT(DISTINCT Order_ID) FROM order_items), 2) AS Avg_Order_Value
FROM order_items;

-- Q41. [KPI] Return rate by category (product quality / fit signal).
SELECT
    Category,
    COUNT(*)                                                            AS Total_Items,
    SUM(CASE WHEN Return_Flag = 'Yes' THEN 1 ELSE 0 END)               AS Returned_Items,
    ROUND(SUM(CASE WHEN Return_Flag = 'Yes' THEN 1 ELSE 0 END) * 100.0
          / COUNT(*), 1)                                                AS Return_Rate_Pct
FROM order_items
GROUP BY Category
ORDER BY Return_Rate_Pct DESC;

-- Q42. [KPI] Churn rate by customer segment (retention health check).
SELECT
    Customer_Segment,
    COUNT(*)                                          AS Total_Customers,
    SUM(Churned)                                       AS Churned_Customers,
    ROUND(SUM(Churned) * 100.0 / COUNT(*), 1)          AS Churn_Rate_Pct
FROM customers
GROUP BY Customer_Segment
ORDER BY Churn_Rate_Pct DESC;
